/// Obfuscates a string literal at compile time and reconstructs it at runtime.
///
/// This macro prevents the plaintext string from appearing directly in the compiled binary
/// or in any code generated by the macro. The input must be a string literal; at compile time
/// it is transformed into obfuscated data, and the generated code decodes it back at runtime.
///
/// - Parameter text: The string literal to obfuscate.
/// - Returns: The original string, reconstructed at runtime from obfuscated data.
///
/// Example:
/// ```swift
/// let token = #obfuscate("my-secret-token")
/// ```
@freestanding(expression)
public macro obfuscate(_ text: String) -> String = #externalMacro(module: "ObfuStringMacros", type: "ObfuStringMacro")

@freestanding(expression)
package macro obfuscate(
    _ text: String,
    algorithmOffset: UInt,
    uuidString: String,
    seed: UInt8,
    deriveKeyFuncName: String,
    decryptFuncName: String
) -> String = #externalMacro(module: "ObfuStringMacros", type: "ObfuStringMacro")
